!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 5.0
  acc_lim_x: 3.0
  acc_lim_y: 3.0
  allow_init_with_backwards_motion: true
  cmd_angle_instead_rotvel: false
  costmap_obstacles_behind_robot_dist: 1.0
  dt_hysteresis: 0.03
  dt_ref: 0.3
  dynamic_obstacle_inflation_dist: 0.5
  enable_multithreading: true
  exact_arc_length: false
  feasibility_check_no_poses: 2
  force_reinit_new_goal_angular: 0.78
  force_reinit_new_goal_dist: 1.0
  free_goal_vel: false
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.2
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          GoalTolerance: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              free_goal_vel: false
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 6
              name: GoalTolerance
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              xy_goal_tolerance: 0.3
              yaw_goal_tolerance: 0.5
            state: []
          HCPlanning: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              enable_multithreading: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              h_signature_prescaler: 0.5
              h_signature_threshold: 0.1
              id: 9
              max_number_classes: 3
              name: HCPlanning
              obstacle_heading_threshold: 0.45
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              roadmap_graph_area_length_scale: 1.0
              roadmap_graph_area_width: 5.0
              roadmap_graph_no_samples: 15
              selection_alternative_time_cost: false
              selection_cost_hysteresis: 1.0
              selection_obst_cost_scale: 1.0
              selection_prefer_initial_plan: 0.95
              selection_viapoint_cost_scale: 1.0
              state: true
              switching_blocking_period: 0.0
              type: ''
              viapoints_all_candidates: true
              visualize_hc_graph: false
            state: []
          Obstacles: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              costmap_obstacles_behind_robot_dist: 1.0
              dynamic_obstacle_inflation_dist: 0.5
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 7
              include_costmap_obstacles: true
              include_dynamic_obstacles: true
              inflation_dist: 0.5
              legacy_obstacle_association: false
              min_obstacle_dist: 0.25
              name: Obstacles
              obstacle_association_cutoff_factor: 5.0
              obstacle_association_force_inclusion_factor: 1.5
              obstacle_poses_affected: 20
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Optimization: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 8
              name: Optimization
              no_inner_iterations: 5
              no_outer_iterations: 4
              obstacle_cost_exponent: 4.0
              optimization_activate: true
              optimization_verbose: false
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              penalty_epsilon: 0.1
              state: true
              type: ''
              weight_acc_lim_theta: 950.0
              weight_acc_lim_x: 100.0
              weight_acc_lim_y: 1.0
              weight_adapt_factor: 2.0
              weight_dynamic_obstacle: 10.0
              weight_dynamic_obstacle_inflation: 0.2
              weight_inflation: 0.2
              weight_kinematics_forward_drive: 200.0
              weight_kinematics_nh: 100.0
              weight_kinematics_turning_radius: 100.0
              weight_max_vel_theta: 760.0
              weight_max_vel_x: 10.0
              weight_max_vel_y: 10.0
              weight_obstacle: 100.0
              weight_optimaltime: 10.0
              weight_shortest_path: 0.0
              weight_viapoint: 1000.0
            state: []
          Recovery: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 10
              name: Recovery
              oscillation_recovery: true
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              shrink_horizon_backup: true
              state: true
              type: ''
            state: []
          Robot: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              acc_lim_theta: 5.0
              acc_lim_x: 3.0
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                dictitems:
                  Carlike: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      cmd_angle_instead_rotvel: false
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 4
                      min_turning_radius: 0.0
                      name: Carlike
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 3
                      state: true
                      type: ''
                      wheelbase: 0.0
                    state: []
                  Omnidirectional: !!python/object/new:dynamic_reconfigure.encoding.Config
                    dictitems:
                      acc_lim_y: 3.0
                      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      id: 5
                      max_vel_y: 0.8
                      name: Omnidirectional
                      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                        state: []
                      parent: 3
                      state: true
                      type: ''
                    state: []
                state: []
              id: 3
              is_footprint_dynamic: false
              max_vel_theta: 5.0
              max_vel_x: 0.8
              max_vel_x_backwards: 0.8
              name: Robot
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Trajectory: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              allow_init_with_backwards_motion: true
              dt_hysteresis: 0.03
              dt_ref: 0.3
              exact_arc_length: false
              feasibility_check_no_poses: 2
              force_reinit_new_goal_angular: 0.78
              force_reinit_new_goal_dist: 1.0
              global_plan_overwrite_orientation: true
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              max_global_plan_lookahead_dist: 1.0
              name: Trajectory
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              publish_feedback: true
              state: true
              teb_autosize: true
              type: ''
              visualize_with_time_as_z_axis_scale: 0.0
            state: []
          ViaPoints: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              global_plan_viapoint_sep: 0.2
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              name: ViaPoints
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
              via_points_ordered: false
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  include_costmap_obstacles: true
  include_dynamic_obstacles: true
  inflation_dist: 0.5
  is_footprint_dynamic: false
  legacy_obstacle_association: false
  max_global_plan_lookahead_dist: 1.0
  max_number_classes: 3
  max_vel_theta: 5.0
  max_vel_x: 0.8
  max_vel_x_backwards: 0.8
  max_vel_y: 0.8
  min_obstacle_dist: 0.25
  min_turning_radius: 0.0
  no_inner_iterations: 5
  no_outer_iterations: 4
  obstacle_association_cutoff_factor: 5.0
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_cost_exponent: 4.0
  obstacle_heading_threshold: 0.45
  obstacle_poses_affected: 20
  optimization_activate: true
  optimization_verbose: false
  oscillation_recovery: true
  penalty_epsilon: 0.1
  publish_feedback: true
  roadmap_graph_area_length_scale: 1.0
  roadmap_graph_area_width: 5.0
  roadmap_graph_no_samples: 15
  selection_alternative_time_cost: false
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_prefer_initial_plan: 0.95
  selection_viapoint_cost_scale: 1.0
  shrink_horizon_backup: true
  switching_blocking_period: 0.0
  teb_autosize: true
  via_points_ordered: false
  viapoints_all_candidates: true
  visualize_hc_graph: false
  visualize_with_time_as_z_axis_scale: 0.0
  weight_acc_lim_theta: 950.0
  weight_acc_lim_x: 100.0
  weight_acc_lim_y: 1.0
  weight_adapt_factor: 2.0
  weight_dynamic_obstacle: 10.0
  weight_dynamic_obstacle_inflation: 0.2
  weight_inflation: 0.2
  weight_kinematics_forward_drive: 200.0
  weight_kinematics_nh: 100.0
  weight_kinematics_turning_radius: 100.0
  weight_max_vel_theta: 760.0
  weight_max_vel_x: 10.0
  weight_max_vel_y: 10.0
  weight_obstacle: 100.0
  weight_optimaltime: 10.0
  weight_shortest_path: 0.0
  weight_viapoint: 1000.0
  wheelbase: 0.0
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.5
state: []
